version: '3.8'
services:
  backend:
    build:
      dockerfile: 'Dockerfile'
    volumes:
      - ./src:/app/src
      - yarn-cache:/usr/local/share/.cache/yarn
    command: yarn migrate-dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@visaeasedb:5432/postgres?schema=public
  db:
    hostname: visaeasedb
    image: postgres:13.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./local-data:/var/lib/postgresql/data
volumes:
  yarn-cache:
